seed_everything: 42
data:
  batch_size: 64
  num_workers: 4
  data_name: MiniMnist
  K: 3 #
  pca_dim: 50  # параметр для уменьшения размерости (data_source)
  n_f_per_cluster: 5 # ?
  l_token: 10 #?
  data_path: /namename/data
model:
  l_token: 50
  num_input_dim: 784
  num_layers_Transformer: 1
  l_token_2: 50
  nu: 1
  preprocess_epoch: 100
  joint_epoch: 200
  E_epochs: 300
  D_epochs: 40
  n_timestep: 100
  lr: 0.001
  weight_decay: 0.0001
  rand_rate: 0.9
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: Diffaug
      project: DIFFAUG_Table
      save_dir: wandb
  #callbacks:
  #  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #    init_args:
  #      monitor: SVC_train
  #      dirpath: ./checkpoints
  #      filename: mini_mnist5-{epoch:03d}-{SVC_train:.5f}
  #      save_top_k: 5
  #      mode: max
  max_epochs: 300
  devices: [0]
  accelerator: gpu
  check_val_every_n_epoch: 20
  enable_checkpointing: False
  enable_progress_bar: True
# trainer.strategy: ddp_find_unused_parameters_true
# trainer.strategy: ddp